// Sri Lankan cities / sub-locations mapped to their district.
// Auto-generated from Sublocations_by_district.xlsx (sheet "All Sub-locations").
// 208 sub-locations across 25 districts.
// Every city name is unique (no city belongs to more than one district), so a
// flat city -> district lookup is unambiguous.

export const CITY_TO_DISTRICT: Record<string, string> = {
  "Colombo 1": "Colombo",
  "Colombo 2": "Colombo",
  "Colombo 3": "Colombo",
  "Colombo 4": "Colombo",
  "Colombo 5": "Colombo",
  "Colombo 6": "Colombo",
  "Colombo 7": "Colombo",
  "Colombo 8": "Colombo",
  "Colombo 9": "Colombo",
  "Colombo 10": "Colombo",
  "Colombo 11": "Colombo",
  "Colombo 12": "Colombo",
  "Colombo 13": "Colombo",
  "Colombo 14": "Colombo",
  "Colombo 15": "Colombo",
  "Talawatugoda": "Colombo",
  "Piliyandala": "Colombo",
  "Battaramulla": "Colombo",
  "Athurugiriya": "Colombo",
  "Kottawa": "Colombo",
  "Nugegoda": "Colombo",
  "Malabe": "Colombo",
  "Boralesgamuwa": "Colombo",
  "Maharagama": "Colombo",
  "Dehiwala": "Colombo",
  "Wellampitiya": "Colombo",
  "Rajagiriya": "Colombo",
  "Homagama": "Colombo",
  "Pannipitiya": "Colombo",
  "Kotte": "Colombo",
  "Kohuwala": "Colombo",
  "Moratuwa": "Colombo",
  "Mount Lavinia": "Colombo",
  "Nawala": "Colombo",
  "Kesbewa": "Colombo",
  "Ratmalana": "Colombo",
  "Kaduwela": "Colombo",
  "Kolonnawa": "Colombo",
  "Angoda": "Colombo",
  "Meegoda": "Colombo",
  "Padukka": "Colombo",
  "Polgasowita": "Colombo",
  "Godagama": "Colombo",
  "Kalubowila": "Colombo",
  "Avissawella": "Colombo",
  "Kotikawatta": "Colombo",
  "Hanwella": "Colombo",
  "Ranala": "Colombo",
  "Nawagamuwa": "Colombo",
  "Olaboduwa": "Colombo",
  "Gampaha City": "Gampaha",
  "Negombo": "Gampaha",
  "Ja-Ela": "Gampaha",
  "Wattala": "Gampaha",
  "Kadawatha": "Gampaha",
  "Kiribathgoda": "Gampaha",
  "Kelaniya": "Gampaha",
  "Kandana": "Gampaha",
  "Ragama": "Gampaha",
  "Katunayake": "Gampaha",
  "Seeduwa": "Gampaha",
  "Minuwangoda": "Gampaha",
  "Nittambuwa": "Gampaha",
  "Veyangoda": "Gampaha",
  "Mirigama": "Gampaha",
  "Divulapitiya": "Gampaha",
  "Ganemulla": "Gampaha",
  "Delgoda": "Gampaha",
  "Kalutara City": "Kalutara",
  "Panadura": "Kalutara",
  "Horana": "Kalutara",
  "Beruwala": "Kalutara",
  "Alutgama": "Kalutara",
  "Wadduwa": "Kalutara",
  "Bandaragama": "Kalutara",
  "Kandy City": "Kandy",
  "Peradeniya": "Kandy",
  "Katugastota": "Kandy",
  "Digana": "Kandy",
  "Pilimatalawa": "Kandy",
  "Gampola": "Kandy",
  "Pussellawa": "Kandy",
  "Nawalapitiya": "Kandy",
  "Kundasale": "Kandy",
  "Pallekele": "Kandy",
  "Gelioya": "Kandy",
  "Ampitiya": "Kandy",
  "Galagedara": "Kandy",
  "Galaha": "Kandy",
  "Deltota": "Kandy",
  "Kadugannawa": "Kandy",
  "Menikhinna": "Kandy",
  "Wattegama": "Kandy",
  "Akurana": "Kandy",
  "Madawala Bazaar": "Kandy",
  "Matale City": "Matale",
  "Nuwara Eliya City": "Nuwara Eliya",
  "Hatton": "Nuwara Eliya",
  "Galle City": "Galle",
  "Hikkaduwa": "Galle",
  "Karapitiya": "Galle",
  "Ahangama": "Galle",
  "Ambalangoda": "Galle",
  "Bentota": "Galle",
  "Baddegama": "Galle",
  "Elpitiya": "Galle",
  "Neluwa": "Galle",
  "Matara City": "Matara",
  "Weligama": "Matara",
  "Akuressa": "Matara",
  "Kekanadurra": "Matara",
  "Dikwella": "Matara",
  "Kamburupitiya": "Matara",
  "Kamburugamuwa": "Matara",
  "Deniyaya": "Matara",
  "Hakmana": "Matara",
  "Gandara": "Matara",
  "Hambantota City": "Hambantota",
  "Tangalla": "Hambantota",
  "Beliatta": "Hambantota",
  "Ambalantota": "Hambantota",
  "Tissamaharama": "Hambantota",
  "Jaffna City": "Jaffna",
  "Nallur": "Jaffna",
  "Chavakachcheri": "Jaffna",
  "Kilinochchi": "Kilinochchi",
  "Mannar": "Mannar",
  "Vavuniya City": "Vavuniya",
  "Mullaitivu": "Mullaitivu",
  "Batticaloa City": "Batticaloa",
  "Eravur": "Batticaloa",
  "Kattankudy": "Batticaloa",
  "Ampara City": "Ampara",
  "Kalmunai": "Ampara",
  "Akkaraipattu": "Ampara",
  "Sammanthurai": "Ampara",
  "Trincomalee City": "Trincomalee",
  "Kinniya": "Trincomalee",
  "Kurunegala City": "Kurunegala",
  "Narammala": "Kurunegala",
  "Kuliyapitiya": "Kurunegala",
  "Ibbagamuwa": "Kurunegala",
  "Wariyapola": "Kurunegala",
  "Giriulla": "Kurunegala",
  "Polgahawela": "Kurunegala",
  "Bingiriya": "Kurunegala",
  "Alawwa": "Kurunegala",
  "Mawathagama": "Kurunegala",
  "Pannala": "Kurunegala",
  "Hettipola": "Kurunegala",
  "Nikaweratiya": "Kurunegala",
  "Galgamuwa": "Kurunegala",
  "Puttalam City": "Puttalam",
  "Chilaw": "Puttalam",
  "Wennappuwa": "Puttalam",
  "Nattandiya": "Puttalam",
  "Dankotuwa": "Puttalam",
  "Marawila": "Puttalam",
  "Anamaduwa": "Puttalam",
  "Anuradhapura City": "Anuradhapura",
  "Kekirawa": "Anuradhapura",
  "Medawachchiya": "Anuradhapura",
  "Tambuttegama": "Anuradhapura",
  "Eppawala": "Anuradhapura",
  "Mihintale": "Anuradhapura",
  "Galnewa": "Anuradhapura",
  "Nochchiyagama": "Anuradhapura",
  "Galenbindunuwewa": "Anuradhapura",
  "Talawa": "Anuradhapura",
  "Habarana": "Anuradhapura",
  "Polonnaruwa City": "Polonnaruwa",
  "Kaduruwela": "Polonnaruwa",
  "Hingurakgoda": "Polonnaruwa",
  "Medirigiriya": "Polonnaruwa",
  "Badulla City": "Badulla",
  "Bandarawela": "Badulla",
  "Welimada": "Badulla",
  "Mahiyanganaya": "Badulla",
  "Ella": "Badulla",
  "Haputale": "Badulla",
  "Hali Ela": "Badulla",
  "Diyatalawa": "Badulla",
  "Passara": "Badulla",
  "Rideemaliyadda": "Badulla",
  "Monaragala City": "Monaragala",
  "Wellawaya": "Monaragala",
  "Bibile": "Monaragala",
  "Buttala": "Monaragala",
  "Kataragama": "Monaragala",
  "Ratnapura City": "Ratnapura",
  "Embilipitiya": "Ratnapura",
  "Balangoda": "Ratnapura",
  "Pelmadulla": "Ratnapura",
  "Eheliyagoda": "Ratnapura",
  "Kuruwita": "Ratnapura",
  "Kahawatta": "Ratnapura",
  "Nivithigala": "Ratnapura",
  "Karawita": "Ratnapura",
  "Kegalle City": "Kegalle",
  "Mawanella": "Kegalle",
  "Warakapola": "Kegalle",
  "Rambukkana": "Kegalle",
  "Galigamuwa": "Kegalle",
  "Ruwanwella": "Kegalle",
  "Dehiowita": "Kegalle",
  "Yatiyantota": "Kegalle",
  "Deraniyagala": "Kegalle",
  "Kitulgala": "Kegalle",
}

// Alphabetically sorted city names for the typeahead.
export const CITIES: string[] = Object.keys(CITY_TO_DISTRICT).sort((a, b) => a.localeCompare(b))

export function districtForCity(city: string): string | undefined {
  return CITY_TO_DISTRICT[city]
}

export function isKnownCity(city: string): boolean {
  return Object.prototype.hasOwnProperty.call(CITY_TO_DISTRICT, city)
}
